CREATE TABLE PERSONAS (

	ID 			INT					,
	NOMBRE 		VARCHAR(50)			,
	APELLIDO1 	VARCHAR(50)			,
	APELLIDO2	VARCHAR(50)			,
	GENDER 		VARCHAR(50)			,
	IP 			VARCHAR(20)			,
	EMAIL 		VARCHAR(50)			,
	SALARIO 	DECIMAL(7,2)		,
	
	PRIMARY KEY (ID)
	
);